module.exports = {
    baseUrl:'/',//根路径
    lintOnSave:false,//关闭ESLint代码检验
    devServer:{
        open:true,//run启动的时候是否弹出页面
        host:'0.0.0.0',//本机地址
        port:'8080',//端口号
        https:false,
        hotOnly:false,
        proxy:{
            //配置跨域
            '/api':{
                target:'http://localhost:8899/',
                ws:true,
                timeout:600000,
                changOrigin:true,
                pathRewrite:{
                    '^/api':'/',
                }
            },
            '/portal':{
                target:'http://111.229.14.128:8898/',
                ws:true,
                timeout:600000,
                changOrigin:true,
                pathRewrite:{
                    '^/portal':'/',
                }
            }
        }
    }
}